var list = [
	{
		"year" : "1",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "2",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "3",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "4",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "5",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "6",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "7",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "8",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "9",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "10",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "11",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "12",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "13",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "14",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "15",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "16",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "17",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "18",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "19",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "20",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "21",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "22",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "23",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "24",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "25",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "26",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "27",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "28",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "29",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "30",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "31",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "32",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "33",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "34",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "35",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "36",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "37",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "38",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "39",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "40",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "41",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "42",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "43",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "44",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "45",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "46",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "47",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "48",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "49",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "50",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "51",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "52",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "53",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "54",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "55",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "56",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "57",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "58",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "59",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "60",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "61",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "52",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "53",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "54",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "55",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "56",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "57",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "58",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "59",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "60",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
{
		"year" : "61",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "52",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "53",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "54",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "55",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "56",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "57",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "58",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "59",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "60",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
{
		"year" : "61",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "52",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "53",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "54",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "55",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "56",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "57",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "58",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "59",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "60",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
{
		"year" : "61",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "52",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "53",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "54",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "55",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "56",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "57",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "58",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "59",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "60",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
	{
		"year" : "60",	
		"class" : "REG",
		"title" : "Method for preparing piezoelectric nanofiber yarn and piezoelectric nanofiber yarn thereby",
		"inventor" : "Woong Ryeol Yu, Sa Rang Park, You Bin Kwon",
		"country" : "South Korea	",
		"date" : "2020.08.06",
		"number" : "1021440990000",
	},
]

function getParameter(name) {
    name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
    var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
        results = regex.exec(location.search);
    return results === null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
}
var pageNum = Number(getParameter("pageNum"));
var listLength = list.length;
var body = $(".tableBox tbody");
var numWrap = $(".nun_wrap");
var count = 10;
var pageLength = 5;
var totalPage = 0;
var startPage = 0;
var endPage = 0;

if(listLength % count == 0){
	totalPage = Math.floor(listLength / count);	
}else{
	totalPage = Math.floor(listLength / count) + 1
}

if(pageNum <= 0){
	pageNum = 1;
	window.location.href="/sub/publications/patents_en.php?pageNum=1";
}else if(pageNum > totalPage ){	pageNum = totalPage;
	window.location.href="/sub/publications/patents_en.php?pageNum="+totalPage+"";	
}

// 마지막 페이지
var finalPage = Math.floor((listLength + (count - 1)) / count); 

// 시작 페이지 (페이징 네비 기준)
var startPage = (Math.floor((pageNum - 1) / pageLength)) * pageLength + 1; 

// 끝 페이지 (페이징 네비 기준)
var endPage = startPage + pageLength - 1; 

// [마지막 페이지 (페이징 네비 기준) > 마지막 페이지] 보다 큰 경우
if (endPage > finalPage) { 
	endPage = finalPage;
}



page(startPage,endPage)
function page(startPage,endPage){
	var ul = numWrap.find("ul");
	var cur = (pageNum * count) - (count - 1);
	for(var i=cur-1; i < pageNum * count; i++){	
		if(i == listLength){
			break;
		}
		var tr = "<tr><td>"+list[i].year+"</td><td>"+list[i].class+"</td><td>"+list[i].title+"</td><td>"+list[i].inventor+"</td><td>"+list[i].country+"</td><td>"+list[i].date+"</td><td>"+list[i].number+"</td></tr>"
		body.append(tr)
	}
	
	/* 페이징 번호 만들기 */
	for(var i=startPage; i<=endPage; i++){
		ul.append('<li><a href="/sub/publications/patents_en.php?pageNum='+i+'">'+i+'</a></li>')
	}

	ul.find("li").each(function(){
		var num = $(this).text();
		if(num == pageNum){
			$(this).addClass("on");
		}
	});

	/* prev / next*/
	if(startPage  > pageLength){
		ul.before('<p class="prev"><a href="/sub/publications/patents_en.php?pageNum='+(startPage - 1)+'">prev</a></p>')
	}
	if(endPage < finalPage){
		ul.after('<p class="next"><a href="/sub/publications/patents_en.php?pageNum='+(endPage+1)+'">next</a></p>')		
	}

}


